SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS CMS_CATEGORY;

DROP TABLE IF EXISTS CMS_CATEGORY_MODEL;

DROP TABLE IF EXISTS CMS_FILE;

DROP TABLE IF EXISTS CMS_MODEL;

DROP TABLE IF EXISTS CMS_MODEL_ATTRIBUTE;

DROP TABLE IF EXISTS CMS_PLACE;

DROP TABLE IF EXISTS CMS_SIMPLE_TYPE;

DROP TABLE IF EXISTS CMS_TEMPLATE;

DROP TABLE IF EXISTS SYS_DOMAIN;

DROP TABLE IF EXISTS SYS_OPERATION_LOG;

DROP TABLE IF EXISTS SYS_ORGANIZATION;

DROP TABLE IF EXISTS SYS_PERMISSION;

DROP TABLE IF EXISTS SYS_PERMISSION_LANG;

DROP TABLE IF EXISTS SYS_ROLE;

DROP TABLE IF EXISTS SYS_ROLE_PERMISSION;

DROP TABLE IF EXISTS SYS_SIMPLE_TYPE;

DROP TABLE IF EXISTS SYS_SITE;

DROP TABLE IF EXISTS SYS_THEME;

DROP TABLE IF EXISTS SYS_USER;

DROP TABLE IF EXISTS SYS_USER_ROLE;

DROP TABLE IF EXISTS SEQUENCE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;