SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

DROP TABLE if EXISTS SYS_PERMISSION_LANG;

DROP TABLE if EXISTS SYS_USER_ROLE;

DROP TABLE if EXISTS SYS_ROLE_PERMISSION;

DROP TABLE if EXISTS SYS_PERMISSION;

DROP TABLE if EXISTS SYS_ROLE;

DROP TABLE if EXISTS SYS_ROLE_PERMISSION;

DROP TABLE if EXISTS SYS_USER;

DROP TABLE if EXISTS SYS_SITE;

DROP TABLE if EXISTS SYS_ORGANIZATION;

DROP TABLE if EXISTS SYS_USER_ROLE;

DROP TABLE if EXISTS SYS_THEME;

DROP TABLE if EXISTS SYS_SIMPLE_TYPE;

DROP TABLE if EXISTS SYS_DOMAIN;

DROP TABLE if EXISTS SEQUENCE;

DROP TABLE if EXISTS CMS_TEMPLATE;

DROP TABLE if EXISTS CMS_SIMPLE_TYPE;

DROP TABLE if EXISTS CMS_PLACE;

DROP TABLE if EXISTS CMS_FILE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;