
DROP PROCEDURE IF EXISTS addSysSimpleType;

DROP PROCEDURE IF EXISTS addCmsSimpleType;

DROP PROCEDURE IF EXISTS addUser;

DROP PROCEDURE IF EXISTS addOrganization;

DROP PROCEDURE IF EXISTS addRole;

DROP PROCEDURE IF EXISTS addUserRole;

DROP PROCEDURE IF EXISTS addPermissionLang;

DROP PROCEDURE IF EXISTS addPermission;

DROP PROCEDURE IF EXISTS addRolePermission;
